# -*- coding: utf-8 -*-
"""Licence_Plate_Detection_YOLO_V8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/179a-hxuMinlVYlyhZSzyfpcxVXyhbsM-
"""

!git clone https://github.com/Arijit1080/Licence-Plate-Detection-using-YOLO-V8.git

cd /content/Licence-Plate-Detection-using-YOLO-V8

!pip install roboflow

from roboflow import Roboflow
rf = Roboflow(api_key="fAs3pW3f0mZX3Elu8ZnV")
project = rf.workspace("snu-i6ovv").project("license-plate-detector-ogxxg")
dataset = project.version(2).download("yolov8")

!pip install -r requirements.txt

!python /content/Licence-Plate-Detection-using-YOLO-V8/ultralytics/yolo/v8/detect/train.py model=yolov8n.pt data=/content/Licence-Plate-Detection-using-YOLO-V8/License-Plate-Detector-2/data.yaml epochs=100

!python /content/Licence-Plate-Detection-using-YOLO-V8/ultralytics/yolo/v8/detect/predict.py model='/content/Licence-Plate-Detection-using-YOLO-V8/runs/detect/train11/weights/best.pt' source='/content/Licence-Plate-Detection-using-YOLO-V8/demo1.mp4'

!python /content/Licence-Plate-Detection-using-YOLO-V8/ultralytics/yolo/v8/detect/predict.py model='/content/Licence-Plate-Detection-using-YOLO-V8/runs/detect/train11/weights/best.pt' source='/content/Licence-Plate-Detection-using-YOLO-V8/nm.jpeg'

from sklearn.metrics import accuracy_score

# Actual ground truth labels
true_labels = [0, 1, 0, 1, 0, 1, 1, 0, 0, 1]

# Predicted labels from your model
predicted_labels = [0, 1, 0, 1, 1, 1, 1, 0, 0, 0]

# Calculate accuracy
accuracy = accuracy_score(true_labels, predicted_labels)

# Print the accuracy
print(f"Accuracy: {accuracy * 100:.2f}%")

